version: "2"
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs1
    container_name: nodejs1
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"

volumes:
  db:
